name = "okb"
description = "Ultra-lightweight (1kb) dark theme for Zola"
license = "MIT"
homepage = "https://github.com/younsl/younsl.github.io"
min_version = "0.18.0"
demo = "https://younsl.github.io"
tags = ["blog", "minimal", "dark", "lightweight"]

[author]
name = "younsl"
homepage = "https://github.com/younsl"

[extra]
author_link = "/about/"
date_format = "%Y-%m-%d"
pinned_to_top = false
